#!/usr/bin/env python3
"""
Auto-refresh YouTube cookies using a headless Playwright browser.

Logs into a Google account (YOUTUBE_EMAIL + YOUTUBE_PASSWORD from .env),
navigates to YouTube, and exports all cookies in Netscape format to cookies.txt.

Run manually:  python refresh_cookies.py
Run via bot:   triggered automatically when cookies are missing or >6 days old.
"""
import asyncio
import os
import sys
import time
import logging
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

_BOT_DIR   = Path(__file__).parent
_COOKIES   = _BOT_DIR / "cookies.txt"
_LOCK_FILE = _BOT_DIR / ".cookie_refresh.lock"
_LOG       = logging.getLogger("cookie_refresh")

YOUTUBE_EMAIL    = os.environ.get("YOUTUBE_EMAIL", "").strip()
YOUTUBE_PASSWORD = os.environ.get("YOUTUBE_PASSWORD", "").strip()

# Max age before a refresh is needed (6 days)
COOKIE_MAX_AGE_SECS = 6 * 24 * 3600


def cookies_need_refresh() -> bool:
    if not _COOKIES.exists():
        return True
    age = time.time() - _COOKIES.stat().st_mtime
    return age > COOKIE_MAX_AGE_SECS


def _write_netscape(cookies: list[dict], path: Path) -> None:
    """Convert Playwright cookie dicts to Netscape cookies.txt format."""
    lines = ["# Netscape HTTP Cookie File\n# Generated by refresh_cookies.py\n"]
    for c in cookies:
        domain    = c.get("domain", "")
        flag      = "TRUE" if domain.startswith(".") else "FALSE"
        path_     = c.get("path", "/")
        secure    = "TRUE" if c.get("secure", False) else "FALSE"
        expires   = int(c.get("expires", 0))
        if expires < 0:
            expires = int(time.time()) + 365 * 24 * 3600
        name      = c.get("name", "")
        value     = c.get("value", "")
        lines.append(f"{domain}\t{flag}\t{path_}\t{secure}\t{expires}\t{name}\t{value}\n")
    path.write_text("".join(lines))


async def refresh() -> bool:
    """Returns True if refresh succeeded."""
    if not YOUTUBE_EMAIL or not YOUTUBE_PASSWORD:
        _LOG.warning("YOUTUBE_EMAIL / YOUTUBE_PASSWORD not set in .env — skipping auto-refresh")
        return False

    # Prevent concurrent refreshes
    if _LOCK_FILE.exists():
        age = time.time() - _LOCK_FILE.stat().st_mtime
        if age < 300:
            _LOG.info("Cookie refresh already in progress, skipping")
            return False
    _LOCK_FILE.touch()

    try:
        from playwright.async_api import async_playwright, TimeoutError as PWTimeout
    except ImportError:
        _LOG.error("playwright not installed — run: pip install playwright && playwright install chromium")
        return False

    _LOG.info("Starting cookie refresh for %s", YOUTUBE_EMAIL)
    success = False

    async with async_playwright() as pw:
        browser = await pw.chromium.launch(
            headless=True,
            args=[
                "--no-sandbox",
                "--disable-dev-shm-usage",
                "--disable-gpu",
                "--disable-extensions",
                "--disable-background-networking",
                "--mute-audio",
            ],
        )
        ctx = await browser.new_context(
            viewport={"width": 1280, "height": 720},
            user_agent=(
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/125.0.0.0 Safari/537.36"
            ),
            locale="en-US",
        )
        page = await ctx.new_page()

        try:
            # ── Step 1: Google login ──────────────────────────────────────────
            _LOG.info("Navigating to Google login...")
            await page.goto("https://accounts.google.com/signin/v2/identifier", timeout=30000)
            await page.wait_for_load_state("networkidle", timeout=20000)

            # Enter email
            email_input = page.locator('input[type="email"]')
            await email_input.wait_for(state="visible", timeout=10000)
            await email_input.fill(YOUTUBE_EMAIL)
            await page.keyboard.press("Enter")
            await page.wait_for_timeout(2000)

            # Enter password
            pw_input = page.locator('input[type="password"]')
            await pw_input.wait_for(state="visible", timeout=10000)
            await pw_input.fill(YOUTUBE_PASSWORD)
            await page.keyboard.press("Enter")
            await page.wait_for_timeout(3000)

            # Check for 2FA or challenge page
            url = page.url
            if "challenge" in url or "signin/v2/challenge" in url:
                _LOG.error("Google login challenge detected (2FA/CAPTCHA). "
                           "Use a Google account with no 2FA for auto-refresh.")
                return False

            # Check we're logged in
            await page.wait_for_url("https://myaccount.google.com/**", timeout=15000)
            _LOG.info("Google login successful")

            # ── Step 2: Navigate to YouTube ───────────────────────────────────
            _LOG.info("Navigating to YouTube...")
            await page.goto("https://www.youtube.com", timeout=30000)
            await page.wait_for_load_state("networkidle", timeout=20000)
            await page.wait_for_timeout(2000)

            # ── Step 3: Export cookies ────────────────────────────────────────
            cookies = await ctx.cookies(["https://youtube.com", "https://www.youtube.com",
                                         "https://music.youtube.com"])
            if not cookies:
                _LOG.error("No cookies found after YouTube navigation")
                return False

            _write_netscape(cookies, _COOKIES)
            _LOG.info("Saved %d cookies to %s", len(cookies), _COOKIES)
            success = True

        except PWTimeout as e:
            _LOG.error("Playwright timeout: %s", e)
        except Exception as e:
            _LOG.error("Cookie refresh failed: %s", e)
        finally:
            await browser.close()

    return success


async def main():
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    if not cookies_need_refresh():
        print("Cookies are fresh — no refresh needed.")
        return
    ok = await refresh()
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    asyncio.run(main())
